

CREATE TABLE [dbo].[SearchCounts](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Term] [varchar](100) NOT NULL,
	[Count] [int] NOT NULL,
 CONSTRAINT [PK__SearchCo__3214EC0755BBC860] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

